#ifndef EEZ_LVGL_UI_VARS_H
#define EEZ_LVGL_UI_VARS_H

#include <stdint.h>
#include <stdbool.h>

#ifdef __cplusplus
extern "C" {
#endif

// enum declarations

typedef enum {
    Player_state_Red = 0,
    Player_state_Green = 1
} Player_state;

// Flow global variables

enum FlowGlobalVariables {
    FLOW_GLOBAL_VARIABLE_PLAYER = 0,
    FLOW_GLOBAL_VARIABLE_BTN_STATE_1 = 1,
    FLOW_GLOBAL_VARIABLE_BTN_STATE_2 = 2,
    FLOW_GLOBAL_VARIABLE_BTN_STATE_3 = 3,
    FLOW_GLOBAL_VARIABLE_BTN_STATE_4 = 4,
    FLOW_GLOBAL_VARIABLE_BTN_STATE_5 = 5,
    FLOW_GLOBAL_VARIABLE_BTN_STATE_6 = 6,
    FLOW_GLOBAL_VARIABLE_BTN_STATE_7 = 7,
    FLOW_GLOBAL_VARIABLE_BTN_STATE_8 = 8,
    FLOW_GLOBAL_VARIABLE_BTN_STATE_9 = 9,
    FLOW_GLOBAL_VARIABLE_BTN_LOCK_1 = 10,
    FLOW_GLOBAL_VARIABLE_BTN_LOCK_2 = 11,
    FLOW_GLOBAL_VARIABLE_BTN_LOCK_3 = 12,
    FLOW_GLOBAL_VARIABLE_BTN_LOCK_4 = 13,
    FLOW_GLOBAL_VARIABLE_BTN_LOCK_5 = 14,
    FLOW_GLOBAL_VARIABLE_BTN_LOCK_6 = 15,
    FLOW_GLOBAL_VARIABLE_BTN_LOCK_7 = 16,
    FLOW_GLOBAL_VARIABLE_BTN_LOCK_8 = 17,
    FLOW_GLOBAL_VARIABLE_BTN_LOCK_9 = 18,
    FLOW_GLOBAL_VARIABLE_USE_MODEL = 19,
    FLOW_GLOBAL_VARIABLE_LOOP_TIMER = 20,
    FLOW_GLOBAL_VARIABLE_LED_POWER = 21
};

// Native global variables



#ifdef __cplusplus
}
#endif

#endif /*EEZ_LVGL_UI_VARS_H*/