/*
*   Implementation of USER NATIVE variables used in the EEZ project.
*   This file allows for the management of global variables that can be accessed
*   and modified from different parts of the code.
*
*   This file is not supplied by EEZ Studio, and must be generated by the user.
*   Code for the variables is suggested by EEZ Studio, and can be copied here or elsewhere.
*/

#include "vars.h"


// Global variables for USER NATIVE variables

int32_t btn_state_1;
int32_t btn_state_2;
int32_t btn_state_3;
int32_t btn_state_4;
int32_t btn_state_5;
int32_t btn_state_6;
int32_t btn_state_7;
int32_t btn_state_8;
int32_t btn_state_9;
int32_t maj_ver;
int32_t min_ver;
int32_t winner;


// Getters for USER NATIVE variables
// These functions are used to get the values of the global variables.

int32_t get_var_btn_state_1() {
    return btn_state_1;
}

int32_t get_var_btn_state_2() {
    return btn_state_2;
}

int32_t get_var_btn_state_3() {
    return btn_state_3;
}

int32_t get_var_btn_state_4() {
    return btn_state_4;
}

int32_t get_var_btn_state_5() {
    return btn_state_5;
}

int32_t get_var_btn_state_6() {
    return btn_state_6;
}

int32_t get_var_btn_state_7() {
    return btn_state_7;
}

int32_t get_var_btn_state_8() {
    return btn_state_8;
}

int32_t get_var_btn_state_9() {
    return btn_state_9;
}

int32_t get_var_maj_ver() {
    return maj_ver;
}

int32_t get_var_min_ver() {
    return min_ver;
}

int32_t get_var_winner() {
    return winner;
}

// Setters for USER NATIVE variables
// These functions are used to set the values of the global variables.

void set_var_btn_state_1(int32_t value) {
    btn_state_1 = value;
}

void set_var_btn_state_2(int32_t value) {
    btn_state_2 = value;
}

void set_var_btn_state_3(int32_t value) {
    btn_state_3 = value;
}

void set_var_btn_state_4(int32_t value) {
    btn_state_4 = value;
}

void set_var_btn_state_5(int32_t value) {
    btn_state_5 = value;
}

void set_var_btn_state_6(int32_t value) {
    btn_state_6 = value;
}

void set_var_btn_state_7(int32_t value) {
    btn_state_7 = value;
}

void set_var_btn_state_8(int32_t value) {
    btn_state_8 = value;
}

void set_var_btn_state_9(int32_t value) {
    btn_state_9 = value;
}

void set_var_maj_ver(int32_t value) {
    maj_ver = value;
}

void set_var_min_ver(int32_t value) {
    min_ver = value;
}

void set_var_winner(int32_t value) {
    winner = value;
}